$kind: http-request
url: "{{baseUrl}}/api/roles"
method: POST
headers:
  Content-Type: application/json
body:
  type: text
  content: |-
    {
      "name": "Support",
      "description": "Support role",
      "permissionIds": []
    }
auth:
  type: bearer
  credentials:
    token: "{{authToken}}"
order: 2000
